spring.application.name=mes-film-gratuits
media.library.path=D:/PlexMedia/PlexMovies

# H2 database (dev)
spring.datasource.url=jdbc:h2:file:./data/mediadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# optional: show SQL while learning
spring.jpa.show-sql=true